[package]
name = "kairo_policy_engine"
version = "0.0.1"
edition = "2024"
published-at = "0xbe11c5cc974ceb27ef7e641d2bb326bafa5a8688fa902032cc4992b5c226e92b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
kairo_governance = { local = "../kairo_governance" }

[addresses]
kairo_policy_engine = "0x0"


