/**
 * Embedded skill file templates shipped with the SDK.
 * Generated by `kairo init` into .cursor/skills/kairo/.
 * All backend URLs are intentionally omitted -- the SDK and CLI
 * resolve the endpoint internally.
 */

export const SKILL_MD = `---
name: kairo
description: Manage Kairo policy-enforced agent wallets. Use when creating wallets, checking vault status, minting policy receipts, or signing transactions through the Kairo SDK/CLI. Default onboarding is dashboard-first: register API key -> create wallet (DKG) in agent -> dashboard auto-binds/provisions policy. Uses @kairo/sdk for non-custodial wallet creation (agent keeps secret share locally).
---

# Kairo — Agent Wallet Management

## Quick Reference

CLI: \`npx kairo <command>\`
SDK reference: \`.cursor/skills/kairo/references/sdk.md\`
API reference: \`.cursor/skills/kairo/references/api.md\`

## Setup

Run the one-line installer (already done if you see this file):
\`\`\`bash
npx @kairo/sdk init <YOUR_KEY>
\`\`\`

The API key is stored in \`~/.kairo/config.json\`. All CLI commands read it automatically.

## Common Workflows

### Check API Health
\`\`\`bash
npx kairo health
\`\`\`

### Dashboard-First Onboarding (Recommended)
1. In dashboard onboarding, create/select policy + governance.
2. In your agent:
\`\`\`bash
npx @kairo/sdk init <YOUR_KEY>
\`\`\`
\`\`\`typescript
import { KairoClient } from "@kairo/sdk";
const kairo = new KairoClient({ apiKey: process.env.KAIRO_API_KEY! });
const wallet = await kairo.createWallet({ curve: "secp256k1" });
\`\`\`
3. Return to dashboard "Verify Connection". Dashboard auto-provisions wallet policy binding + vault registration.

### Create a Policy (Advanced / Self-Managed)
\`\`\`bash
npx kairo policy-create --stable-id "my-policy" --allow "0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18"
\`\`\`
Then register the version:
\`\`\`bash
npx kairo policy-register --policy-id "0x..."
\`\`\`

### Create Wallet (via SDK)
For wallet creation, use the Node.js SDK (handles DKG client-side):
\`\`\`typescript
import { KairoClient } from "@kairo/sdk";
const kairo = new KairoClient({ apiKey: process.env.KAIRO_API_KEY! });
const wallet = await kairo.createWallet({ curve: "secp256k1" });
\`\`\`
See \`.cursor/skills/kairo/references/sdk.md\` for full SDK docs.

### Provision Wallet into Vault
Requires: policy version registered first.
\`\`\`bash
npx kairo vault-provision --wallet-id "0x..." --policy-id "0x..." --stable-id "my-policy"
\`\`\`

### Mint Policy Receipt
\`\`\`bash
npx kairo receipt-mint --policy-id "0x..." --binding-id "0x..." --destination "0x742d35Cc..." --intent-hash "0xabab..."
\`\`\`

### Check Vault Status
\`\`\`bash
npx kairo vault-status --wallet-id "0x..."
\`\`\`

### View Audit Events
\`\`\`bash
npx kairo audit --limit 20
\`\`\`

## Full Agent Flow (Dashboard-First)

1. \`npx @kairo/sdk init <YOUR_KEY>\` — store API key, install skill
2. Create/select policy in dashboard onboarding
3. Configure governance approvers in dashboard onboarding (optional)
4. Create wallet via SDK \`createWallet()\` — runs DKG locally, secret share stays on agent
5. Dashboard Verify step auto-provisions wallet with selected policy
6. \`npx kairo receipt-mint\` — request policy check for a transaction
7. Sign via SDK — both shares combine, only if policy allows

## Advanced: Self-Managed Flow (CLI Heavy)

1. \`npx @kairo/sdk init <YOUR_KEY>\`
2. \`npx kairo policy-create\`
3. \`npx kairo policy-register\`
4. SDK \`createWallet()\`
5. \`npx kairo vault-provision\`

## Trust Model

- Agent's key share stays local (\`~/.kairo/keys/\`)
- Server's key share stays on Kairo backend
- Neither party can sign alone
- Policy engine gates every transaction before server releases its share
- All policy decisions are on-chain (Sui) and verifiable

## Troubleshooting

- **401 Unauthorized**: API key missing/invalid or not registered in backend key store. Re-run \`npx @kairo/sdk init <YOUR_KEY>\` with a valid key.
- **403 Forbidden: key does not own wallet**: Wallet wasn't created/provisioned with this API key (ownership mismatch).
- **429 Rate limit**: Public Sui RPC throttled — use Shinami or own RPC provider.
- **MoveAbort code 102**: Policy version not registered — call \`npx kairo policy-register\` before \`vault-provision\`.
- **\`nonce too low\` / \`already known\`**: Rapid reruns or duplicate raw tx; wait for pending tx, then re-sign and rebroadcast.
- **AwaitingKeyHolderSignature**: Wallet needs activation after DKG — SDK activation flow required.
`;

export const API_REFERENCE_MD = `# Kairo API Reference

## Authentication
All write endpoints require \`X-Kairo-Api-Key\` header.
The CLI reads the key from \`~/.kairo/config.json\` automatically.
Open endpoints: \`/health\`, \`/api/vault/info\`, \`/api/vault/status/:id\`, \`/api/audit/events\`

## Key Registration
\`\`\`bash
npx kairo register --label "my-agent"
\`\`\`

## Wallet Creation (via SDK)
The SDK handles DKG client-side. Agent keeps their secret share locally.
\`\`\`typescript
import { KairoClient } from "@kairo/sdk";
const kairo = new KairoClient({ apiKey: process.env.KAIRO_API_KEY! });
const wallet = await kairo.createWallet({ curve: "secp256k1" });
// wallet.walletId, wallet.address
\`\`\`

## Policy Management

### Create Policy
\`\`\`bash
npx kairo policy-create --stable-id "my-policy" --version "1.0.0" --allow "0x<address>"
\`\`\`

Rule types:
- \`1\` = MaxNativeValue (max single transaction value)
- \`10\` = PeriodLimit (cumulative spend limit per time window)

### Register Policy Version
\`\`\`bash
npx kairo policy-register --policy-id "0x..."
\`\`\`

### Get Policy Details
\`\`\`bash
npx kairo policy-details --policy-id "0x..."
\`\`\`

## Vault

### Provision (atomic binding + vault registration)
\`\`\`bash
npx kairo vault-provision --wallet-id "0x..." --policy-id "0x..." --stable-id "my-policy"
\`\`\`
Note: Register policy version BEFORE calling provision.

### Check Status
\`\`\`bash
npx kairo vault-status --wallet-id "0x..."
\`\`\`

## Receipt Minting
\`\`\`bash
npx kairo receipt-mint --policy-id "0x..." --binding-id "0x..." --destination "0x..." --intent-hash "0x..."
\`\`\`
Namespace: 1=EVM, 2=Bitcoin, 3=Solana

## Utility
\`\`\`bash
npx kairo health          # Server health
npx kairo audit --limit 20  # Recent audit events
\`\`\`
`;

export const SDK_REFERENCE_MD = `# Kairo SDK Reference

## Installation
\`\`\`bash
npm install @kairo/sdk
\`\`\`

Requires: \`@ika.xyz/sdk\`, \`@mysten/sui\`

## KairoClient

\`\`\`typescript
import { KairoClient } from "@kairo/sdk";

const kairo = new KairoClient({
  apiKey: process.env.KAIRO_API_KEY!,
  storePath: "~/.kairo/keys",        // local secret share storage (default)
  network: "testnet",                 // or "mainnet"
  suiRpcUrl: "https://...",           // optional, defaults to public testnet
});
\`\`\`

### createWallet(opts?)
Creates a dWallet via client-side DKG. Secret share stays local.

\`\`\`typescript
const wallet = await kairo.createWallet({
  curve: "secp256k1",           // or "ed25519" for Solana
});
// Returns: { walletId, address, curve, bindingObjectId?, createdAt }
\`\`\`

Dashboard-first default: create wallet in agent and let dashboard onboarding handle policy provisioning.

Advanced optional params are still supported:
\`\`\`typescript
const wallet = await kairo.createWallet({
  curve: "secp256k1",
  policyObjectId: "0x...",
  stableId: "my-policy",
});
\`\`\`

### listWallets()
Lists all wallets in local key store.
\`\`\`typescript
const wallets = kairo.listWallets();
\`\`\`

### getWallet(walletId)
Gets a specific wallet from local store.
\`\`\`typescript
const w = kairo.getWallet("0x...");
\`\`\`

## BackendClient (HTTP wrapper)
Lower-level HTTP client for direct API calls.

\`\`\`typescript
import { BackendClient } from "@kairo/sdk";

const client = new BackendClient({ apiKey: "your-key" });

await client.register("my-agent");
await client.getHealth();
await client.submitDKG({...});
await client.getDKGStatus(requestId);
await client.provision({...});
await client.mintReceipt({...});
\`\`\`

## KeyStore (local storage)
File-based secret share storage at \`~/.kairo/keys/\`.

\`\`\`typescript
import { KeyStore } from "@kairo/sdk";

const store = new KeyStore("~/.kairo/keys");
store.save(record);
store.load("0x...");
store.list();
store.delete("0x...");
\`\`\`

## Trust Model
- Agent's secret share -> stored locally (KeyStore), never sent to server
- Server's share -> held by Kairo backend
- Full signing -> requires BOTH shares + policy approval
- Kairo alone cannot sign (missing agent share)
- Agent alone cannot sign (missing server share)
`;
